### ISSUE TITLE
Delete unnecessary files

### ISSUE THREAD

**Issue by harshit98** [harshit98/useful-libraries#2]
- Boost library
- Tokenize.cpp

The aim of the repo is to keep only useful libraries which are used a lot, known and easy to understand.

**Comment by ReekyMarko** [comment]
You mean one should open a PR with these files removed? Sounds like an easy grab for hacktoberfest if it's true :wink:

**Comment by harshit98** [comment]
Yep. You can proceed if you want @ReekyMarko :)
